### ISSUE TITLE
Plugin Config Values

### ISSUE THREAD

**Issue by romton843** [tkurki/signalk-to-influxdb2#11]
Hi Teppo,
I have another plugin to write to influxdb2 and it is working fine but it hasn't been updated in a long time and I wanted to use yours instead.
I used the same configuration as the other plugin (URL, token, Organisation, Bucket...) but it is not working.
I didn't add gzipThreshold, maxBatchBytes, exponentialBase or any HTTP headers since I didn't know what to put. Is it something needed?
Here is my configuration.
Please let me know if you see something obvious.
Sorry to bother you with that and thank you for your great work.
Best regards.
Romain

Url
http://localhost:8086

Authentication token
PZgGQwoJlXiZpeEHtxDL62ZJe-sDFpwUYvbdoG_uHsR3KbdNUv0U0MoH7oe7s_WabE6Sy9uhuAaQ7sPDVjs6MQ====

Organisation
8e63af9d3843ee9d

Bucket
6824a8eca8241954

batchSize
1000

flushInterval
30000

gzipThreshold

maxBatchBytes

consistency
any

maxRetries
3

maxRetryTime
540000

maxBufferLines
32000

retryJitter
200

minRetryDelay
5000

maxRetryDelay
180000

exponentialBase

randomRetry
X

**Comment by tkurki** [comment]
Try adding just the minimal configuration: url, token, org and bucket.

How do you know it is not working - see any errors on the Dashboard or server log?

**Comment by tkurki** [comment]
You can start from scratch by removing $HOME/.signalk/plugin-config-data/signalk-to-influxdb2.json and restarting the server.

**Comment by romton843** [comment]
Thank you for your response.
I tried to erase the parameters, remove the json file, update the plugin to today's version, create a new token, new organisation, new bucket but it didn't solve the issue.
I know it is not working because there is no tag keys found in the data explorer of infludb (I try to look the same way I do with the other plugin).
There is one error message created in the log when the plugin starts but then nothing else, hopefully it'll be useful:

v [HttpError]: organization name "8e63af9d3843ee9d" not found at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:16:3875) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) { statusCode: 404, statusMessage: 'Not Found', body: '{\n' + '\t"code": "not found",\n' + '\t"message": "organization name \\"8e63af9d3843ee9d\\" not found"\n' + '}', contentType: 'application/json; charset=utf-8', json: { code: 'not found', message: 'organization name "8e63af9d3843ee9d" not found' }, code: 'not found', _retryAfter: 0 }

**Comment by tkurki** [comment]
Well, the log message says your org is not correct.

**Comment by romton843** [comment]
I see, I put the Organization ID instead of Name. Sorry about that.
It works now. Thank you very much.
Let me know if there is anything I can do to help.
Regards.
Romain

**Comment by tkurki** [comment]
If Signal K is valuable to you consider supporting our work at https://opencollective.com/signalk
