### ISSUE TITLE
Select data: Allow only some OR deny some

### ISSUE THREAD

**Issue by Hurevincent** [tkurki/signalk-to-influxdb2#27]
How is it possible to write in database only selected item?
For exemple , I want to store in the database only SOG, because actualy the plugin send|all the data avalaible in signalk server.

**Comment by tkurki** [comment]
That is not yet possible. I plan to add that over the coming winter, unless someone beats me to it.

**Comment by Krecik7** [comment]
Is it possible to back with this problem ? Like it was in Influx1 plugin
Ignore All
Send only selected manually pathes. 

This option which is now - 'ignore with regexp', i do have to try build one big regexp query:
^(?!electrical|environment).*$ to exclude this pathes from excluded list, when we need only - i.e - 20 pathes to be sent do influx2, from 300 that we have in system, to save a/ space, b/ lifetime of sd card. then 'allow' list would be much better -)

What do you think ?

**Comment by tkurki** [comment]
Certainly doable

**Comment by tkurki** [comment]
@scurvy-dog an incoming datum is ignored (not written) if the path matches an ignored path OR the source matches an ignored source. It does not matter which is applied first. Or am I missing something here?

Regular expressions are such a complex subject that I am not especially keen to start documenting them. If you can provide a documentation snippet with examples that you'd want to add please do so, I am not strictly against it. But please open another issue, as this is a bit separate from this issue.

btw you can have chatgpt write regexps for you, translating from english to regexp. It will even include an explanation of how it works!

**Comment by tkurki** [comment]
Please see and comment on #66, where I am addressing the need to pick some paths in addition to not writing some.

**Comment by tkurki** [comment]
No comments? You asked for it, but nobody shows an interest for the feature now?
