### ISSUE TITLE
Include timestamp when pushing data to influxdb

### ISSUE THREAD

**Issue by macjl** [tkurki/signalk-to-influxdb2#42]
Hello,

I’m trying to replay old SignalK logs, and push them to InfluxDB. These logs are timestamped, and I can see the path value in SignalK is in the past.

But when the signalk-t9-influxdb2 push datas to InfluxDB, the timestamp seems to be lost, and all data are at current date. Is it a normal behavior ?

**Comment by tkurki** [comment]
Just that I happened to implement this as default behavior and haven’t gotten around to adding the other way as an option.
