### ISSUE TITLE
Retry if InfluxDB is not available upon plugin startup

### ISSUE THREAD

**Issue by tkurki** [tkurki/signalk-to-influxdb2#52]
Currently the plugin never retries the connection if initial connection fails on startup.

**Comment by wegscheider** [comment]
Could it be that this is also the issue reported on the openmarine/openplotter forum:

...Rpi 5 running openplotter 4. After boot in the signal k dashboard it just says for signalk-to-influxdb2 "started" and no data is written to influxdb. When I restart signal k or go to the plugin configuration and press (w/o doing any changes) "submit", then the corresponding influxdb bucket is displayed and data is written. This works up to the next reboot.
