### ISSUE TITLE
Delay of raw ingest to influxDB

### ISSUE THREAD

**Issue by DrStS** [tkurki/signalk-to-influxdb2#57]
How can I configure the delay until a value is written to influxDB. For example, when I receive a temp. which upates every 2s in the signalK dataExplorer there seems to be a pretty long delay (~30sec) until these values are written to influxdb. Moreover, the delay seems to have a random behaviour.

I use the most recent version of singalK and the plugin.

Thanks a lot for your help. 

Best

**Comment by tkurki** [comment]
Influxdb client writes the buffer to db every 60 seconds or max number of points. The params are the in the plugin config, batch something. On my phone so can’t provide the exact param name.

**Comment by DrStS** [comment]
Thanks a lot for the info: 
![Screenshot 2024-03-28 085143](https://github.com/tkurki/signalk-to-influxdb2/assets/18216396/190be432-4eb0-4d8a-8bc6-1373b86a4535)
I have played with these settings. Yet it seems there is no change. I would like that the data is updated every 5 sec. Thanks a lot! Best Stefan

**Comment by tkurki** [comment]
Lol, looks like these are not passed to influx client! I’ll get back to you.

**Comment by DrStS** [comment]
Thanks!

**Comment by tkurki** [comment]
Should be fixed in 1.7.2.

**Comment by DrStS** [comment]
Thanks! I can confrim. It works now!
