### ISSUE TITLE
Changing data type over time in incoming data

### ISSUE THREAD

**Issue by tkurki** [tkurki/signalk-to-influxdb2#7]
failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.destination.commonName" is type float, already exists as type string dropped=1

**Comment by philseeley** [comment]
Hi @tkurki, this is something I'm seeing a lot on these values:

"navigation.courseOverGroundTrue"
"navigation.magneticVariation"
"navigation.speedOverGround"

I've checked the InfluxDB for navigation.speedOverGround and as far as I can tell all the existing values are floats.

Is there any debug/info I can provide to help you with this?

Cheers
Phil

Full error is:
```
Feb 23 17:40:26 openplotter signalk-server[454]: ERROR: Write to InfluxDB failed. m [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.speedOverGround" is type float, already exists as type string dropped=87
Feb 23 17:40:26 openplotter signalk-server[454]:     at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671)
Feb 23 17:40:26 openplotter signalk-server[454]:     at IncomingMessage.emit (node:events:539:35)
Feb 23 17:40:26 openplotter signalk-server[454]:     at endReadableNT (node:internal/streams/readable:1345:12)
Feb 23 17:40:26 openplotter signalk-server[454]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Feb 23 17:40:26 openplotter signalk-server[454]:   statusCode: 422,
Feb 23 17:40:26 openplotter signalk-server[454]:   statusMessage: 'Unprocessable Entity',
Feb 23 17:40:26 openplotter signalk-server[454]:   body: '{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \\"value\\" on measurement \\"navigation.speedOverGround\\" is type float, already exists as type string dropped=87"}',
Feb 23 17:40:26 openplotter signalk-server[454]:   contentType: 'application/json; charset=utf-8',
Feb 23 17:40:26 openplotter signalk-server[454]:   json: {
Feb 23 17:40:26 openplotter signalk-server[454]:     code: 'unprocessable entity',
Feb 23 17:40:26 openplotter signalk-server[454]:     message: 'failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.speedOverGround" is type float, already exists as type string dropped=87'
Feb 23 17:40:26 openplotter signalk-server[454]:   },
Feb 23 17:40:26 openplotter signalk-server[454]:   code: 'unprocessable entity',
Feb 23 17:40:26 openplotter signalk-server[454]:   _retryAfter: 0
Feb 23 17:40:26 openplotter signalk-server[454]: }

```

**Comment by tkurki** [comment]
@philseeley what did you mean by _I've checked the InfluxDB for navigation.speedOverGround and as far as I can tell all the existing values are floats_? That the values that you see in InfluxDb are actually floats and not strings? That does not make sense, given your error message. Or did you mean something else?

**Comment by philseeley** [comment]
Hi @tkurki, I retrieved all the data using this query:
```
from(bucket: "cielo")
  |> range(start: 2009-01-02T23:00:00Z, stop: 2025-01-02T23:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "navigation.speedOverGround")
```
and got this header which shows "_value:float":
```
pi@openplotter:~ $ influx query -f q | head
Result: _result
Table: keys: [_start, _stop, _field, _measurement, context, self, source]
                   _start:time                      _stop:time           _field:string                  _measurement:string                      context:string             self:string           source:string                  _value:float                      _time:time
------------------------------  ------------------------------  ----------------------  -----------------------------------  ----------------------------------  ----------------------  ----------------------  ----------------------------  ------------------------------
```
As you say, that doesn't make sense given the error. But I also got some more debug yesterday where the log was showing the same type mismatch error on "navigation.courseOverGroundMagnetic":
```
Feb 27 11:00:05 openplotter signalk-server[461]: ERROR: Write to InfluxDB failed. m [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.courseOverGroundMagnetic" is type float, already exists as type string dropped=4
Feb 27 11:00:05 openplotter signalk-server[461]:     at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671)
Feb 27 11:00:05 openplotter signalk-server[461]:     at IncomingMessage.emit (node:events:539:35)
Feb 27 11:00:05 openplotter signalk-server[461]:     at endReadableNT (node:internal/streams/readable:1345:12)
Feb 27 11:00:05 openplotter signalk-server[461]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Feb 27 11:00:05 openplotter signalk-server[461]:   statusCode: 422,
Feb 27 11:00:05 openplotter signalk-server[461]:   statusMessage: 'Unprocessable Entity',
Feb 27 11:00:05 openplotter signalk-server[461]:   body: '{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \\"value\\" on measurement \\"navigation.courseOverGroundMagnetic\\" is type float, already exists as type string dropped=4"}',
Feb 27 11:00:05 openplotter signalk-server[461]:   contentType: 'application/json; charset=utf-8',
Feb 27 11:00:05 openplotter signalk-server[461]:   json: {
Feb 27 11:00:05 openplotter signalk-server[461]:     code: 'unprocessable entity',
Feb 27 11:00:05 openplotter signalk-server[461]:     message: 'failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.courseOverGroundMagnetic" is type float, already exists as type string dropped=4'
Feb 27 11:00:05 openplotter signalk-server[461]:   },
Feb 27 11:00:05 openplotter signalk-server[461]:   code: 'unprocessable entity',
Feb 27 11:00:05 openplotter signalk-server[461]:   _retryAfter: 0
Feb 27 11:00:05 openplotter signalk-server[461]: }
```
But executing the following query:
```
pi@openplotter:~ $ cat q
from(bucket: "cielo")
  |> range(start: 2009-01-02T23:00:00Z, stop: 2025-01-02T23:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "navigation.courseOverGroundMagnetic")
```
got an internal error from influxdb:
```
pi@openplotter:~ $ influx query -f q 
Error: failed to execute query: 500 Internal Server Error: panic: runtime error: invalid memory address or nil pointer dereference
```
but I was able to delete all the data with:
```
influx delete -b cielo --start 2009-01-02T23:00:00Z --stop 2025-01-02T23:00:00Z -p '_measurement="navigation.courseOverGroundMagnetic"'
```
and then everything started working OK. So could it be an influxdb issue?

One thing I've never been happy with in my setup is the setting of the system time. As we're often offshore and don't have NTP available I'm using the signalk set-system-time plugin. I've tried setting it to only set the time once (interval 0) which should wait for a GPS time, but that doesn't work and sets the time back to 2003. So I've currently got it setting the time every 60 seconds, but I've recently seen discussions that this could be a second or more out, which in itself isn't a problem, but if it could set the time "back" a second or so, then perhaps influxdb (which is all about time ordered values) is getting confused by this.

I might be way off the mark, but my setup is a very simple OpenPlotter install with signalk writing everything to influxdb using your plugin. So the only thing that I might have got different is the time setup. I've also just noticed that I have time coming from 3 separate GPS sources and don't know which the set-system-time would use and one of them is often a number of seconds behind the others:

![navigation-datetime](https://user-images.githubusercontent.com/21173301/221790462-ae581b57-2350-4578-9480-a85af36fc8f3.png)

Prior to using the Raspberry Pi I was running signalk, influxdb and grafana from my laptop, which having a real-time clock didn't need the set-system-time plugin and I don't remember seeing this error then.

Hope all that helps.

Cheers
Phil

**Comment by ostroesser** [comment]
I'm having this issue too:


My GPS sometimes spits outs 'null' values for courseOverGroudTrue. It just so happens that when i activated the plugin for the first time that field was null so it got cast into string type.

Now this measurement only accepts null values :
![null_influxdb](https://user-images.githubusercontent.com/4171436/222087132-1ffd36a2-eab1-4954-85ef-c824fec0c81d.png)

The error in the logs 👍 
`ERROR: Write to InfluxDB failed. m [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.courseOverGroundTrue" is type float, already exists as type string dropped=1 at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) { statusCode: 422, statusMessage: 'Unprocessable Entity', body: '{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \\"value\\" on measurement \\"navigation.courseOverGroundTrue\\" is type float, already exists as type string dropped=1"}', contentType: 'application/json; charset=utf-8', json: { code: 'unprocessable entity', message: 'failure writing points to database: partial write: field type conflict: input field "value" on measurement "navigation.courseOverGroundTrue" is type float, already exists as type string dropped=1' }, code: 'unprocessable entity', _retryAfter: 0 }`

Cheers,
Olivier

**Comment by tkurki** [comment]
Version 1.1 improves handling numeric values for paths in the SK schema, preventing inserting nulls treated as objects and values that are not numeric.

**Comment by tkurki** [comment]
No idea about the influx error.

set-system-time issues seem separate to me, even if they pertain to data in influxd => https://github.com/SignalK/set-system-time/issues/14 would be my idea for a remedy.

Server's Source Priorities should sort your multiple datetime source issue => Server / Connections configuration page.

**Comment by tkurki** [comment]
Oh, note that Data Browser is not real time, it refreshes periodically, so not an accurate way to compare latest values. Though I still don't quite understand how you would end up with that much difference between your data source. InstrumentPanel is closer to realtime / update-as-new-data-arrives.

**Comment by philseeley** [comment]
@tkurki thanks for all the info. I've now restricted the GPS to a single source so the time is now being updated more consistently and so far I've not seen the data type mismatch error👍

I'll keep an eye on it, but so far the evidence seems to be that fluctuating time might be causing internal influxdb errors which are leading to data type mismatch errors for clients.
